<?php
/**
 * Adds hreflang tags for language and regional URLs used by search engines.
 *
 * @see https://support.google.com/webmasters/answer/189077
 * @see https://jira.pluswerk.ag/browse/ROL-140
 */
?>
<?php
if ($block->isEnabled()):

foreach ($block->getAlternateLinks() as $alternateLink): ?>
    <link rel="alternate" href="<?= $alternateLink->getUrl(); ?>" hreflang="<?= $alternateLink->getCode(); ?>">
<?php endforeach; endif; ?>