<?php
/**
 * Adds hreflang tags for language and regional URLs used by search engines.
 *
 * @see https://support.google.com/webmasters/answer/189077
 * @see https://jira.pluswerk.ag/browse/ROL-140
 */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $viewModel \MageSuite\SeoHreflang\ViewModel\Hreflang */
$viewModel = $block->getViewModel();
?>
<?php foreach ($viewModel->getAlternateLinks() as $alternateLink) : ?>
    <link rel="alternate" href="<?= $escaper->escapeHtml($alternateLink->getUrl()); ?>" hreflang="<?= $escaper->escapeHtml($alternateLink->getCode()); ?>">
<?php endforeach;?>
