<?php
$objectManager = \Magento\TestFramework\Helper\Bootstrap::getObjectManager();

$category = $objectManager->create('Magento\Catalog\Model\Category');
$category->isObjectNew(true);
$category
    ->setId(100)
    ->setCreatedAt('2014-06-23 09:50:07')
    ->setName('Active Category')
    ->setParentId(2)
    ->setPath('1/2/333')
    ->setLevel(3)
    ->setAvailableSortBy('name')
    ->setDefaultSortBy('name')
    ->setUrlKey('active_category')
    ->setIsActive(true)
    ->setPosition(1)
    ->setAvailableSortBy(['position'])
    ->setMetaDescription('Meta description')
    ->save()
    ->reindex();

/** @var \Magento\UrlRewrite\Model\UrlRewrite $urlRewrite */
$urlRewrite = $objectManager->create(\Magento\UrlRewrite\Model\UrlRewrite::class);
$urlRewrite->setEntityType('custom')
    ->setRequestPath('rewrite_for_active_category.html')
    ->setTargetPath('catalog/category/view/id/' . $category->getId())
    ->setRedirectType(0)
    ->setStoreId(2)
    ->setDescription(null)
    ->setIsAutogenerated(0);

$urlRewrite->save();
