<?php
$objectManager = \Magento\TestFramework\Helper\Bootstrap::getObjectManager();

$product = $objectManager->create(\Magento\Catalog\Model\Product::class);
$product->setTypeId(\Magento\Catalog\Model\Product\Type::TYPE_SIMPLE)
    ->setId(100)
    ->setAttributeSetId(4)
    ->setName('Active Product')
    ->setSku('active_product')
    ->setPrice(10)
    ->setVisibility(\Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH)
    ->setStatus(\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED)
    ->setUrlKey('active_product')
    ->setWebsiteIds([1])
    ->setStoreIds([1])
    ->setStockData(['use_config_manage_stock' => 1, 'qty' => 100, 'is_qty_decimal' => 0, 'is_in_stock' => 1])
    ->setCanSaveCustomOptions(true)
    ->setDescription('<p>Description</p>')
    ->save();

$product->reindex();

/** @var \Magento\UrlRewrite\Model\UrlRewrite $urlRewrite */
$urlRewrite = $objectManager->create(\Magento\UrlRewrite\Model\UrlRewrite::class);
$urlRewrite->setEntityType('custom')
    ->setRequestPath('rewrite_for_active_product.html')
    ->setTargetPath('catalog/product/view/id/' . $product->getId())
    ->setRedirectType(0)
    ->setStoreId(2)
    ->setDescription(null)
    ->setIsAutogenerated(0);

$urlRewrite->save();
